### ISSUE TITLE
[Feature Request] Clarity on 'Search in Workspace'

### ISSUE THREAD

**Issue by Amoursol** [andydandy74/Monito#45]
**What is the problem that needs solving?**
![image](https://user-images.githubusercontent.com/12857357/49037578-9f952c80-f188-11e8-88e2-764ba18c87f6.png)

The typology (Text, Group, Node etc) is at the end of each line of text here: i.e 'xyz [Text note]'

**How would you like to see it solved?**
Create a new WPF grid at the start that holds the typology first - and if you click on that it further filters the search. First filter = Text match. Second filter = Typology.

**Comment by Amoursol** [comment]
Ah cool - had seen that before when I played but it skipped me this time! That's better. Agree that a grid-column for simple UI clean-up is useful still.

**Comment by andydandy74** [comment]
Need to add a type property to ```ObjectInWorkspace``` class that can be used to populate the first cell of each Grid. This will affect multiple tools.

**Comment by andydandy74** [comment]
@Amoursol - This will be in the next release.
![grafik](https://user-images.githubusercontent.com/3014437/51081901-0e5c2400-16fc-11e9-9131-8c069e16f955.png)

**Comment by Amoursol** [comment]
Awesome stuff @andydandy74! Looks very slick 🥇
